[0m09:26:10.431010 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC066A6120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC066A59D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC066A6510>]}


============================== 09:26:10.436050 | 9b07e176-7c33-4dd4-ab62-5824776ceaf2 ==============================
[0m09:26:10.436050 [info ] [MainThread]: Running with dbt=1.7.9
[0m09:26:10.436050 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\paulo\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:27:23.485739 [debug] [MainThread]: Starter project path: c:\Users\paulo\dbt_test\.venv\Lib\site-packages\dbt\include\starter_project
[0m09:27:23.515239 [info ] [MainThread]: 
Your new dbt project "dbt_pitie" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:27:23.515239 [info ] [MainThread]: Setting up your profile.
[0m09:27:27.208990 [debug] [MainThread]: Command `dbt init` succeeded at 09:27:27.208990 after 76.90 seconds
[0m09:27:27.208990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC00090DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC06330BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC064ED730>]}
[0m09:27:27.211543 [debug] [MainThread]: Flushing usage events
[0m09:45:26.248048 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000144291D97F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000144285F6540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000144291D9D60>]}


============================== 09:45:26.252163 | 61abc0d0-1c63-4eb8-8716-035f12f83495 ==============================
[0m09:45:26.252163 [info ] [MainThread]: Running with dbt=1.7.9
[0m09:45:26.253177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\paulo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:45:26.254756 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\paulo\dbt_test\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:45:26.255802 [debug] [MainThread]: Command `dbt run` failed at 09:45:26.255802 after 0.12 seconds
[0m09:45:26.255802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000144290819A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000144290AFBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014428F8A510>]}
[0m09:45:26.256814 [debug] [MainThread]: Flushing usage events
